#DATABASE CONNECTION (LOCAL DEVELOPMENT ONLY)
spring.datasource.url=jdbc:postgresql://localhost:5432/friendly-expense-tracker
spring.datasource.username=postgres
spring.datasource.password=postgreadmin
spring.datasource.driver-class-name=org.postgresql.Driver
#ENABLE AUTO-START
spring.sql.init.mode=always
#DISABLE AUTOMATIC SCHEMA GENERATION
spring.jpa.hibernate.ddl-auto=none
#SHOW SQL QUERIES IN CONSOLE
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true=always

#JWT SECRET KEY (LOCAL DEVELOPMENT ONLY)
app.jwt.secret=fhj37898ylxbnsk32067mlaqwewc431zkhnj48563h4cks623hr76jkvc632hdi45jhlmlbjndy3
#TOKENS EXPIRE IN 24HS
app.jwt.expiration-ms=86400000

#RESEND
app.resend.api-key=re_PSo5cxAX_BS45TNtKQjsPNqAKsGFYbhbX
app.resend.from-email=onboarding@resend.dev
app.frontend.url=http://localhost:5173

spring.jpa.open-in-view=false