#DATABASE CONNECTION
spring.datasource.url=jdbc:postgresql://localhost:5432/friendly-expense-tracker
spring.datasource.username=postgres
spring.datasource.password=postgreadmin
spring.datasource.driver-class-name=org.postgresql.Driver
#ENABLE AUTO-START
spring.sql.init.mode=always
#DISABLE AUTOMATIC SCHEMA GENERATION
spring.jpa.hibernate.ddl-auto=none
#SHOW SQL QUERIES IN CONSOLE
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true=always

spring.jpa.open-in-view=false